print ("Madlib Maker")
rOne= input("name: ")
rTwo= input("noun: ")
rThree= input("color: ")
rFour= input("noun: ")
rFive= input("action verb: ")
rSix= input("action verb: ")

print("There once was a person named",rOne,"that lived in a",rTwo)
print(rOne,"had long",rThree,"hair")
print("The",rTwo,"was the size of a",rFour)
print(rOne,"loved to",rFive,"and",rSix,"in the",rTwo)
print(rOne,"lived happily ever after in the",rTwo)